#pragma once

#include <cstdint>

enum class MESSAGE_TYPE_ENUM : uint32_t {
    MBIM_OPEN_MSG = 1,
    MBIM_CLOSE_MSG = 2,
    MBIM_COMMAND_MSG = 3,
    MBIM_HOST_ERROR_MSG = 4,
    MBIM_OPEN_DONE = 0x80000001,
    MBIM_CLOSE_DONE = 0x80000002,
    MBIM_COMMAND_DONE = 0x80000003,
    MBIM_FUNCTION_ERROR_MSG = 0x80000004,
    MBIM_INDICATE_STATUS_MSG = 0x80000007
};

enum class MESSAGE_QUERY_OR_SET_ENUM : uint32_t {
    QUERY,
    SET 
};

enum class MBIM_PROTOCOL_ERROR_CODES_ENUM : uint32_t {
    MBIM_ERROR_TIMEOUT_FRAGMENT = 1,
    MBIM_ERROR_FRAGMENT_OUT_OF_SEQUENCE,
    MBIM_ERROR_LENGTH_MISMATCH,
    MBIM_ERROR_DUPLICATED_TID,
    MBIM_ERROR_NOT_OPENED,
    MBIM_ERROR_UNKNOW,
    MBIM_ERROR_CANCEL,
    MBIM_ERROR_MAX_TRANSFER
};

enum class MBIM_STATUS_TO_HOST_ENUM : uint32_t {
    MBIM_STATUS_SUCCESS = 0,
    MBIM_STATUS_BUSY = 1,
    MBIM_STATUS_FAILURE = 2,
    MBIM_STATUS_SIM_NOT_INSERTED = 3,
    MBIM_STATUS_BAD_SIM = 4,
    MBIM_STATUS_PIN_REQUIRED = 5,
    MBIM_STATUS_PIN_DISABLED = 6,
    MBIM_STATUS_NOT_REGISTERED = 7,
    MBIM_STATUS_PROVIDERS_NOT_FOUND = 8,
    MBIM_STATUS_NO_DEVICE_SUPPORT = 9,
    MBIM_STATUS_PROVIDER_NOT_VISIBLE = 10,
    MBIM_STATUS_DATA_CLASS_NOT_AVAILABLE = 11,
    MBIM_STATUS_PACKET_SERVICE_DETACHED = 12,
    MBIM_STATUS_MAX_ACTIVATED_CONTEXTS = 13,
    MBIM_STATUS_NOT_INITIALIZED = 14,
    MBIM_STATUS_VOICE_CALL_IN_PROGRESS = 15,
    MBIM_STATUS_CONTEXT_NOT_ACTIVATED = 16,
    MBIM_STATUS_SERVICE_NOT_ACTIVATED = 17,
    MBIM_STATUS_INVALID_ACCESS_STRING = 18,
    MBIM_STATUS_INVALID_USER_NAME_PWD = 19,
    MBIM_STATUS_RADIO_POWER_OFF = 20,
    MBIM_STATUS_INVALID_PARAMETERS = 21,
    MBIM_STATUS_READ_FAILURE = 22,
    MBIM_STATUS_WRITE_FAILURE = 23,
    // Reserved = 24
    MBIM_STATUS_NO_PHONEBOOK = 25,
    MBIM_STATUS_PARAMETER_TOO_LONG = 26,
    MBIM_STATUS_STK_BUSY = 27,
    MBIM_STATUS_OPERATION_NOT_ALLOWED = 28,
    MBIM_STATUS_MEMORY_FAILURE = 29,
    MBIM_STATUS_INVALID_MEMORY_INDEX = 30,
    MBIM_STATUS_MEMORY_FULL = 31,
    MBIM_STATUS_FILTER_NOT_SUPPORTED = 32,
    MBIM_STATUS_DSS_INSTANCE_LIMIT = 33,
    MBIM_STATUS_INVALID_DEVICE_SERVICE_OPERATION = 34,
    MBIM_STATUS_AUTH_INCORRECT_AUTN = 35,
    MBIM_STATUS_AUTH_SYNC_FAILURE = 36,
    MBIM_STATUS_AUTH_AMF_NOT_SET = 37,
    MBIM_STATUS_SMS_UNKNOWN_SMSC_ADDRESS = 100,
    MBIM_STATUS_SMS_NETWORK_TIMEOUT = 101,
    MBIM_STATUS_SMS_LANG_NOT_SUPPORTED = 102,
    MBIM_STATUS_SMS_ENCODING_NOT_SUPPORTED = 103,
    MBIM_STATUS_SMS_FORMAT_NOT_SUPPORTED = 104
};
