#pragma once

#include <cstdint>

namespace MBIM_CMD {

struct UUID_BASIC_CONNECT {
    static constexpr const char* UUID = "a289cc33bcbb8b4fb6b0133ec2aae6df";
    enum CID {
        MBIM_CID_DEVICE_CAPS                  = 1,
        MBIM_CID_SUBSCRIBER_READY_STATUS      = 2,
        MBIM_CID_RADIO_STATE                  = 3,
        MBIM_CID_PIN                          = 4,
        MBIM_CID_PIN_LIST                     = 5,
        MBIM_CID_HOME_PROVIDER                = 6,
        MBIM_CID_PREFERRED_PROVIDERS          = 7,
        MBIM_CID_VISIBLE_PROVIDERS            = 8,
        MBIM_CID_REGISTER_STATE               = 9,
        MBIM_CID_PACKET_SERVICE               = 10,
        MBIM_CID_SIGNAL_STATE                 = 11,
        MBIM_CID_CONNECT                      = 12,
        MBIM_CID_PROVISIONED_CONTEXTS         = 13,
        MBIM_CID_SERVICE_ACTIVATION           = 14,
        MBIM_CID_IP_CONFIGURATION             = 15,
        MBIM_CID_DEVICE_SERVICES              = 16,
        MBIM_CID_DEVICE_SERVICE_SUBSCRIBE_LIST = 19,
        MBIM_CID_PACKET_STATISTICS            = 20,
        MBIM_CID_NETWORK_IDLE_HINT            = 21,
        MBIM_CID_EMERGENCY_MODE               = 22,
        MBIM_CID_IP_PACKET_FILTERS            = 23,
        MBIM_CID_MULTICARRIER_PROVIDERS       = 24
    };
};

struct UUID_SMS {
    static constexpr const char* UUID = "533fbeeb14fe44679f9033a223e56c3f";
    enum CID {
        MBIM_CID_SMS_CONFIGURATION       = 1,
        MBIM_CID_SMS_READ                = 2,
        MBIM_CID_SMS_SEND                = 3,
        MBIM_CID_SMS_DELETE              = 4,
        MBIM_CID_SMS_MESSAGE_STORE_STATUS = 5
    };
};

struct UUID_USSD {
    static constexpr const char* UUID = "e550a0c85e82479e82f710abf4c3351f";
    enum CID {
        MBIM_CID_USSD = 1
    };
};

struct UUID_PHONEBOOK {
    static constexpr const char* UUID = "4bf384761e6a41dbb1d8bed289c25bdb";
    enum CID {
        MBIM_CID_PHONEBOOK_CONFIGURATION = 1,
        MBIM_CID_PHONEBOOK_READ          = 2,
        MBIM_CID_PHONEBOOK_DELETE        = 3,
        MBIM_CID_PHONEBOOK_WRITE         = 4
    };
};

struct UUID_STK {
    static constexpr const char* UUID = "d8f20131fcb54e178602d6ed3816164c";
    enum CID {
        MBIM_CID_STK_PAC               = 1,
        MBIM_CID_STK_TERMINAL_RESPONSE = 2,
        MBIM_CID_STK_ENVELOPE          = 3
    };
};

struct UUID_AUTH {
    static constexpr const char* UUID = "1d2b5ff70aa148b2aa5250f15767174e";
    enum CID {
        MBIM_CID_AKA_AUTH  = 1,
        MBIM_CID_AKAP_AUTH = 2,
        MBIM_CID_SIM_AUTH  = 3
    };
};

struct UUID_DSS {
    static constexpr const char* UUID = "c08a26dd7718438284826e0d583c4d0e";
    enum CID {
        MBIM_CID_DSS_CONNECT = 1
    };
};

}

enum class MESSAGE_TYPE_ENUM : uint32_t {
    MBIM_OPEN_MSG = 1,
    MBIM_CLOSE_MSG = 2,
    MBIM_COMMAND_MSG = 3,
    MBIM_HOST_ERROR_MSG = 4,
    MBIM_OPEN_DONE = 0x80000001,
    MBIM_CLOSE_DONE = 0x80000002,
    MBIM_COMMAND_DONE = 0x80000003,
    MBIM_FUNCTION_ERROR_MSG = 0x80000004,
    MBIM_INDICATE_STATUS_MSG = 0x80000007
};

enum class MESSAGE_QUERY_OR_SET_ENUM : uint32_t {
    QUERY,
    SET 
};

enum class MBIM_PROTOCOL_ERROR_CODES_ENUM : uint32_t {
    MBIM_ERROR_TIMEOUT_FRAGMENT = 1,
    MBIM_ERROR_FRAGMENT_OUT_OF_SEQUENCE,
    MBIM_ERROR_LENGTH_MISMATCH,
    MBIM_ERROR_DUPLICATED_TID,
    MBIM_ERROR_NOT_OPENED,
    MBIM_ERROR_UNKNOW,
    MBIM_ERROR_CANCEL,
    MBIM_ERROR_MAX_TRANSFER
};

enum class MBIM_STATUS_TO_HOST_ENUM : uint32_t {
    MBIM_STATUS_SUCCESS = 0,
    MBIM_STATUS_BUSY = 1,
    MBIM_STATUS_FAILURE = 2,
    MBIM_STATUS_SIM_NOT_INSERTED = 3,
    MBIM_STATUS_BAD_SIM = 4,
    MBIM_STATUS_PIN_REQUIRED = 5,
    MBIM_STATUS_PIN_DISABLED = 6,
    MBIM_STATUS_NOT_REGISTERED = 7,
    MBIM_STATUS_PROVIDERS_NOT_FOUND = 8,
    MBIM_STATUS_NO_DEVICE_SUPPORT = 9,
    MBIM_STATUS_PROVIDER_NOT_VISIBLE = 10,
    MBIM_STATUS_DATA_CLASS_NOT_AVAILABLE = 11,
    MBIM_STATUS_PACKET_SERVICE_DETACHED = 12,
    MBIM_STATUS_MAX_ACTIVATED_CONTEXTS = 13,
    MBIM_STATUS_NOT_INITIALIZED = 14,
    MBIM_STATUS_VOICE_CALL_IN_PROGRESS = 15,
    MBIM_STATUS_CONTEXT_NOT_ACTIVATED = 16,
    MBIM_STATUS_SERVICE_NOT_ACTIVATED = 17,
    MBIM_STATUS_INVALID_ACCESS_STRING = 18,
    MBIM_STATUS_INVALID_USER_NAME_PWD = 19,
    MBIM_STATUS_RADIO_POWER_OFF = 20,
    MBIM_STATUS_INVALID_PARAMETERS = 21,
    MBIM_STATUS_READ_FAILURE = 22,
    MBIM_STATUS_WRITE_FAILURE = 23,
    // Reserved = 24
    MBIM_STATUS_NO_PHONEBOOK = 25,
    MBIM_STATUS_PARAMETER_TOO_LONG = 26,
    MBIM_STATUS_STK_BUSY = 27,
    MBIM_STATUS_OPERATION_NOT_ALLOWED = 28,
    MBIM_STATUS_MEMORY_FAILURE = 29,
    MBIM_STATUS_INVALID_MEMORY_INDEX = 30,
    MBIM_STATUS_MEMORY_FULL = 31,
    MBIM_STATUS_FILTER_NOT_SUPPORTED = 32,
    MBIM_STATUS_DSS_INSTANCE_LIMIT = 33,
    MBIM_STATUS_INVALID_DEVICE_SERVICE_OPERATION = 34,
    MBIM_STATUS_AUTH_INCORRECT_AUTN = 35,
    MBIM_STATUS_AUTH_SYNC_FAILURE = 36,
    MBIM_STATUS_AUTH_AMF_NOT_SET = 37,
    MBIM_STATUS_SMS_UNKNOWN_SMSC_ADDRESS = 100,
    MBIM_STATUS_SMS_NETWORK_TIMEOUT = 101,
    MBIM_STATUS_SMS_LANG_NOT_SUPPORTED = 102,
    MBIM_STATUS_SMS_ENCODING_NOT_SUPPORTED = 103,
    MBIM_STATUS_SMS_FORMAT_NOT_SUPPORTED = 104
};

enum class DEVICE_TYPE_ENUM : uint32_t {
    MBIM_DEVICE_TYPE_UNKNOWN,
    MBIM_DEVICE_TYPE_EMBEDDED,
    MBIM_DEVICE_TYPE_REMOVABLE,
    MBIM_DEVICE_TYPE_REMOTE
};

enum class CELLULAR_CLASS_ENUM : uint32_t {
    MBIM_CELLULAR_CLASS_GSM = 1,
    MBIM_CELLULAR_CLASS_CDMA
};

enum class VOICE_CLASS_ENUM : uint32_t {
    MBIM_VOICE_CLASS_UNKNOWN = 1,
    MBIM_VOICE_CLASS_NO_VOICE,
    MBIM_VOICE_CLASS_SEPARATE_VOICE_DATA,
    MBIM_VOICE_CLASS_SIMULTANEOUS_VOICE_DATA
};


enum class SIM_CLASS_ENUM : uint32_t {
    MBIM_SIM_CLASS_SIM_LOGICAL = 1,
    MBIM_SIM_CLASS_SIM_REMOVABLE
};

enum class DATA_CLASS_ENUM : uint32_t {
    MBIM_DATA_CLASS_NONE         = 0x00000000,
    MBIM_DATA_CLASS_GPRS         = 0x00000001,
    MBIM_DATA_CLASS_EDGE         = 0x00000002,
    MBIM_DATA_CLASS_UMTS         = 0x00000004,
    MBIM_DATA_CLASS_HSDPA        = 0x00000008,
    MBIM_DATA_CLASS_HSUPA        = 0x00000010,
    MBIM_DATA_CLASS_LTE          = 0x00000020,
    MBIM_DATA_CLASS_1XRTT        = 0x00010000,
    MBIM_DATA_CLASS_1XEVDO       = 0x00020000,
    MBIM_DATA_CLASS_1XEVDO_REVA  = 0x00040000,
    MBIM_DATA_CLASS_1XEVDV       = 0x00800000,
    MBIM_DATA_CLASS_3XRTT        = 0x01000000,
    MBIM_DATA_CLASS_1XEVDO_REVB  = 0x02000000,
    MBIM_DATA_CLASS_UMB          = 0x04000000,
    MBIM_DATA_CLASS_CUSTOM       = 0x80000000
};

enum class SMS_CAPS_ENUM : uint32_t {
    MBIM_SMS_CAPS_NONE           = 0,
    MBIM_SMS_CAPS_PDU_RECEIVE    = 1,
    MBIM_SMS_CAPS_PDU_SEND       = 2,
    MBIM_SMS_CAPS_TEXT_RECEIVE   = 4,
    MBIM_SMS_CAPS_TEXT_SEND      = 8
};

enum class CTRL_CAPS_ENUM : uint32_t {
    MBIM_CTRL_CAPS_NONE              = 0,
    MBIM_CTRL_CAPS_REG_MANUAL        = 1,
    MBIM_CTRL_CAPS_HW_RADIO_SWITCH   = 2,
    MBIM_CTRL_CAPS_CDMA_MOBILE_IP    = 4,
    MBIM_CTRL_CAPS_CDMA_SIMPLE_IP    = 8,
    MBIM_CTRL_CAPS_MULTI_CARRIER     = 16
};

// todo:  fix capitalizing
enum class SUBSCRIBER_READY_STATE_ENUM : uint32_t {
    MBIMSubscriberReadyStateNotInitialized = 0,
    MBIMSubscriberReadyStateInitialized,
    MBIMSubscriberReadyStateSimNotInserted,
    MBIMSubscriberReadyStateBadSim,
    MBIMSubscriberReadyStateFailure,
    MBIMSubscriberReadyStateNotActivated,
    MBIMSubscriberReadyStateDeviceLocked
};

enum class MBIM_READY_INFO_FLAGS_ENUM : uint32_t {
    MBIMReadyInfoFlagsNone = 0,
    MBIMReadyInfoFlagsProtectUniqueID
};

enum class MBIM_RADIO_SWITCH_STATE_ENUM : uint32_t {
    MBIM_RADIO_OFF = 0,
    MBIM_RADIO_ON
};